### ISSUE TITLE
连接已存在的MySQL数据库失败

### ISSUE THREAD

**Issue by pppfz** [Deeptrain-Community/chatnio#29]
# 现象描述
1、在[1panel的面板](https://github.com/1Panel-dev/1Panel)环境下，已经安装MySQL和redis服务器在1panel-network(1panel面板的默认网络)。且我的MySQL、redis、chatnio在同一个网段，可以ping通。
```json
{
    "Name": "1panel-network",
    "Id": "ded70d4xxxxxxxxxxxxxxxxxxxxxxxxxx0815",
    "Created": "xxxxxxxxxx",
    "Scope": "local",
    "Driver": "bridge",
    "EnableIPv6": false,
    "IPAM": {
      "Driver": "default",
      "Options": null,
      "Config": [
        {
          "Subnet": "172.18.0.0/16",
          "Gateway": "172.18.0.1"
        }
      ]
    },
    "Internal": false,
    "Attachable": false,
    "Ingress": false,
    "ConfigFrom": {
      "Network": ""
    },
    "ConfigOnly": false,
    "Containers": {
      "0b8f6fxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx2e3379e": {
        "Name": "chatnio",
        "EndpointID": "ee76bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx17a64a79293f",
        "MacAddress": "02:42:ac:12:00:0d",
        "IPv4Address": "172.18.0.13/16",
        "IPv6Address": ""
      },
      "0b9f1e9ffxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx6df76f7550b7": {
        "Name": "mysql",
        "EndpointID": "460678adb4xxxxxxxxxxxxxxxxxxxxxxxxxxxx9dfe5f645c7e79e10",
        "MacAddress": "02:42:ac:12:00:08",
        "IPv4Address": "172.18.0.8/16",
        "IPv6Address": ""
      },
      "d7cef7b56bafa71xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxc295cd17985ea": {
        "Name": "redis",
        "EndpointID": "9f9a8aefxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx958f5fea",
        "MacAddress": "02:42:ac:12:00:09",
        "IPv4Address": "172.18.0.9/16",
        "IPv6Address": ""
      }
    },
    "Options": {},
    "Labels": {}
  }
```
![image](https://github.com/Deeptrain-Community/chatnio/assets/119300926/ec931d99-b45e-4546-b899-d0b445dfe43e)

使用的配置文件：

```yml
version: '3'
services:
  chatnio:
      image: programzmh/chatnio
      container_name: chatnio
      restart: always
      ports:
          - "8000:8094"
      environment:
          MYSQL_HOST: mysql
          MYSQL_USER: chanio
          MYSQL_PASSWORD: xxxxxxxxxxxx
          MYSQL_DATABASE: chanio
          REDIS_HOST: redis
          REDIS_PORT: 6379
          REDIS_PASSWORD: ""
          REDIS_DB: 0
          SERVE_STATIC: "true"
      volumes:
        - ./config:/config
        - ./logs:/logs

networks:
  1panel-network:
      external: true
```
> 这里的数据库和用户名就是`chanio`
![image](https://github.com/Deeptrain-Community/chatnio/assets/119300926/8141b3a9-476d-435c-b2f0-9da6baadbcbd)
# 数据库连接检测
在MySQL容器中，成功连接数据库
![image](https://github.com/Deeptrain-Community/chatnio/assets/119300926/47e55c84-8031-42a3-8822-4c29edd5b7b7)

# 报错
报错如下：
```
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

2023/12/26 08:59:24 [connection] failed to connect to mysql server: mysql, will retry in 5 seconds
2023/12/26 08:59:29 [connection] failed to connect to mysql server: mysql, will retry in 5 seconds
2023/12/26 08:59:34 [connection] failed to connect to mysql server: mysql, will retry in 5 seconds
2023/12/26 08:59:39 [connection] failed to connect to mysql server: mysql, will retry in 5 seconds
2023/12/26 08:59:44 [connection] failed to connect to mysql server: mysql, will retry in 5 seconds
2023/12/26 08:59:49 [connection] failed to connect to mysql server: mysql, will retry in 5 seconds
2023/12/26 08:59:54 [connection] failed to connect to mysql server: mysql, will retry in 5 seconds

```
# 问题
请问，我的问题是什么，该怎么修改。
