### ISSUE TITLE
希望能支持星火3.5

### ISSUE THREAD

**Issue by ilay1678** [Deeptrain-Community/chatnio#96]
应该很好适配，和前几个版本相比就换了接口地址和模型

**Comment by zmh-program** [comment]
感谢建议 不过讯飞v3.5多模态支持识图 我想等有空一起支持一下

**Comment by ilay1678** [comment]
当前星火模型报错 
```
[WARNING] - [2024-03-11 08:40:33] - caught panic from chat handler: runtime error: invalid memory address or nil pointer dereference (instance: spark-desk-v3, client: )
goroutine 169 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
chat/manager.ChatHandler.func1()
	/backend/manager/chat.go:61 +0x5d
panic({0x10d76a0, 0x1a7a610})
	/usr/local/go/src/runtime/panic.go:884 +0x213
chat/adapter/sparkdesk.getChoice(0x1390da0?)
	/backend/adapter/sparkdesk/chat.go:82 +0xca
chat/adapter/sparkdesk.(*ChatInstance).CreateStreamChatRequest(0xc0001800a0, 0xc001063500, 0xc000a4c020)
	/backend/adapter/sparkdesk/chat.go:133 +0x599
chat/adapter.createChatRequest({0x139d710, 0xc000125ee0}, 0xc001884240, 0x1093f60?)
	/backend/adapter/adapter.go:106 +0xce5
chat/adapter.NewChatRequest({0x139d710, 0xc000125ee0}, 0xc001884240, 0x11fdb83?)
	/backend/adapter/request.go:25 +0x48
chat/channel.NewChatRequest({0x11fdb83?, 0xc0008312f7?}, 0xc001884240, 0xc0001828e0?)
	/backend/channel/worker.go:22 +0x186
chat/channel.NewChatRequestWithCache(0xc0008312f7?, 0xd?, {0x11fdb83, 0x3}, 0xc001884240, 0x139e018?)
	/backend/channel/worker.go:88 +0xf5
chat/manager.ChatHandler(0xc0000c5d40, 0x4f0692?, 0xc000422140)
	/backend/manager/chat.go:90 +0x537
chat/manager.ChatAPI.func1(0x0?)
	/backend/manager/manager.go:87 +0x145
chat/manager.(*Connection).Process(0xc0000c5d40, 0xc0000c5d70)
	/backend/manager/connection.go:140 +0x59
created by chat/manager.(*Connection).Handle
	/backend/manager/connection.go:150 +0x78
```

**Comment by zmh-program** [comment]
修复，但是这个问题一般不常见

**Comment by zmh-program** [comment]
是所有请求都报错这个么？如果是的话 请截图一下渠道配置（记得打码）

**Comment by ilay1678** [comment]
> 是所有请求都报错这个么？如果是的话 请截图一下渠道配置（记得打码密钥）

是的
```
id: 7
      name: 讯飞星火
      type: sparkdesk
      priority: 0
      weight: 1
      models:
        - spark-desk-v3
      retry: 3
      secret: 123456
      endpoint: wss://spark-api.xf-yun.com
      mapper: ""
      state: true
      group: []
      reflect: {}
      hitmodels:
        - spark-desk-v3
      excludemodels: []
      currentsecret: 123456
```
